name: Deploy to Cloud Run Dev revision

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: us-central1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/main_server:$GITHUB_SHA
      
      - name: Deploy
        run: gcloud beta run deploy $PROJECT_ID --image gcr.io/$PROJECT_ID/main_server:$GITHUB_SHA --platform managed --region $RUN_REGION --no-traffic --tag dev