name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: us-central1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          export_default_credentials: true

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/main_server:${{ steps.vars.outputs.sha_short }}
        working-directory: ./app
      
      - name: Deploy
        run: gcloud run deploy $PROJECT_ID --image gcr.io/$PROJECT_ID/main_server:${{ steps.vars.outputs.sha_short }} --platform managed --region $RUN_REGION --quiet
      
      - name: Route Traffic
        run: gcloud run services update-traffic $PROJECT_ID --to-revisions LATEST=100 --platform managed --region $RUN_REGION