name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: us-central1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}

jobs:
  build:
    name: Build container image and push to GCP Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          export_default_credentials: true

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Link Docker with GCP Container Registry
        run: gcloud auth configure-docker

      - name: Build
        run: >
          docker build
          --tag gcr.io/$PROJECT_ID/main_server:${{ steps.vars.outputs.sha_short }}
          --tag gcr.io/$PROJECT_ID/main_server:latest
          .
        working-directory: ./app

      - name: Push to Container Registry
        run: >
          docker push gcr.io/$PROJECT_ID/main_server

  deploy:
    needs: [build]
    name: Deploy new container
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          export_default_credentials: true
      - name: Deploy
        run: >
          gcloud run deploy $PROJECT_ID
          --image gcr.io/$PROJECT_ID/main_server:latest
          --platform managed
          --region $RUN_REGION
          --quiet

  route:
    needs: [deploy]
    name: Route traffic to new version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          export_default_credentials: true
      - name: Route Traffic
        run: >
          gcloud run services update-traffic $PROJECT_ID 
          --to-revisions LATEST=100 
          --platform managed 
          --region $RUN_REGION
